### PR TITLE
symlink mpi so we can just do -lmpi and find it in a default search path

### PR DESCRIPTION
**Pull request by PhilipDeegan**
this is to get around https://github.com/LLNL/SAMRAI/issues/222

### CODE REVIEW

**Comment by jeandet** [comment]
I think it's better if you merge all RUN statements in one because docker produces one layer per statement and it may increase the image build time on CI.

**Comment by PhilipDeegan** [comment]
> I think it's better if you merge all RUN statements in one because docker produces one layer per statement and it may increase the image build time on CI.

good to know, in this case it's just some symlinks so I doubt it would do much to the build time, but I will update it

**Comment by PhilipDeegan** [comment]
actually I think I'll just have a shell script copied in a build time, it should just be a single layer

**Comment by PhilipDeegan** [comment]
This is tested and can be seen [here](https://hephaistos.lpp.polytechnique.fr/teamcity/buildConfiguration/Phare_TestBuildDockerDepImages/77243?buildTab=log&focusLine=121&logView=flowAware&linesState=64)

**Review by jeandet — APPROVED** [review]

**Pull request merged**
